// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/addTodo.ts";
import * as $$$$$$$$$1 from "./actions/checkTodo.ts";
import * as $$$$$$$$$2 from "./actions/removeTodo.ts";
import * as $$$$$$$$$3 from "./actions/signIn.ts";
import * as $$$$$$$$$4 from "./actions/signUp.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$3 from "./apps/site.ts";
import * as $$$0 from "./loaders/todos.ts";
import * as $$$$$$0 from "./sections/Footer.tsx";
import * as $$$$$$1 from "./sections/ItWorks.tsx";
import * as $$$$$$2 from "./sections/SignIn.tsx";
import * as $$$$$$3 from "./sections/SignUp.tsx";
import * as $$$$$$4 from "./sections/Theme/Theme.tsx";
import * as $$$$$$5 from "./sections/ToDoList.tsx";

const manifest = {
  "loaders": {
    "site/loaders/todos.ts": $$$0,
  },
  "sections": {
    "site/sections/Footer.tsx": $$$$$$0,
    "site/sections/ItWorks.tsx": $$$$$$1,
    "site/sections/SignIn.tsx": $$$$$$2,
    "site/sections/SignUp.tsx": $$$$$$3,
    "site/sections/Theme/Theme.tsx": $$$$$$4,
    "site/sections/ToDoList.tsx": $$$$$$5,
  },
  "actions": {
    "site/actions/addTodo.ts": $$$$$$$$$0,
    "site/actions/checkTodo.ts": $$$$$$$$$1,
    "site/actions/removeTodo.ts": $$$$$$$$$2,
    "site/actions/signIn.ts": $$$$$$$$$3,
    "site/actions/signUp.ts": $$$$$$$$$4,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/deco/records.ts": $$$$$$$$$$$2,
    "site/apps/site.ts": $$$$$$$$$$$3,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
